version: "3"

dotenv:
  - .env

tasks:
  day1:
    desc: "Day 1"
    dir: cmd/day01
    cmds:
      - echo "Using $AOC_SESSION"
      - go run main.go

  day2:
    desc: "Day 2"
    dir: cmd/day02
    cmd: go run main.go

  day3:
    desc: "Day 3"
    dir: cmd/day03
    cmd: go run main.go
